Use GSettings
gi-lom/dialect pull request #42
Opened 2020-10-03 15:46 UTC by rafaelmardojai

Fix #36
Related to #40 

**What does this PR?**

- Added the GSettings schema with all the keys needed for now.
- Start using GSettings to save used languages
- Remove history saving

Note: we have an inconsistency problem with strings, there's a mixed use of `""` and `''`. This PR use the second, but we must establish which one we are going to use.

2020-10-03 15:59 UTC, fushinari commented
Language saving isn't working as intended. I wanted to look at it right away but it might have to wait until tomorrow. The issue is like so:
- Right languages aren't changing at all.
- Left languages only change on language switch. 

I don't know the older behavior and I don't know if I broke it in the earlier cleanup but that's how it is right now. :(

2020-10-03 16:11 UTC, rafaelmardojai commented
For me it works fine, the only issue is that the latest left lang is forgotten and the app always starts with "Auto".

2020-10-04 13:53 UTC, fushinari requested changes
Some minor changes are needed. But other than that, LGTM.

About the misbehavior I mentioned earlier, that was just me sleep-talking :laughing: . Sorry, in fact, it does work as expected.

Also, the `json` import is now unnecessary.

2020-10-04 13:53 UTC, fushinari commented on src/main.py
> +        if len(self.history) > 0:
Since history is now always an empty list on start, this check won't be necessary anymore. We can just set the left buffer to "".

2020-10-04 13:53 UTC, fushinari commented on src/main.py
> +        if len(self.history) > 0:
See comment above. But this time for right buffer,

2020-10-04 13:53 UTC, fushinari commented on src/main.py
> +                                     GLib.Variant('as', self.left_langs))
Under-indented by 7 columns.

2020-10-04 13:53 UTC, fushinari commented on src/main.py
> +                                     GLib.Variant('as', self.right_langs))
Over-indented by one column.

2020-10-04 13:53 UTC, fushinari commented on src/main.py
> +                                     GLib.Variant('as', self.left_langs))
Over-indented by one column.

2020-10-04 14:00 UTC, fushinari commented
Sorry, I didn't realize I have commit permissions and half-jokingly pushed... But well... it got pushed.

2020-10-04 14:01 UTC, rafaelmardojai commented
Looks like I'm having indentation issues in my editor 😂 everything looked fine here.

2020-10-04 14:01 UTC, fushinari approved these changes

2020-10-04 14:01 UTC, fushinari commented
It's fine. It was too minor anyway. Gonna merge now.

2020-10-04 14:02 UTC, rafaelmardojai commented
Wait, I will move the live translation to use GSettings.

2020-10-04 14:02 UTC, fushinari commented
> Wait, I will move the live translation to use GSettings.

Oh wait. That wasn't done? I almost missed that.

2020-10-04 14:03 UTC, fushinari commented
Okay, go ahead.

2020-10-04 14:09 UTC, rafaelmardojai commented
Ready to merge.

2020-10-04 14:26 UTC, merged