Gtk.Buider Rewrite
gi-lom/dialect pull request #43
Opened 2020-10-05 04:10 UTC by rafaelmardojai

**Actual changes:**

- Split a little bit more the source (main.py, define.py and window.py)
- Add libhandy dependency
- Use Gtk.Builder for about dialog
- Add a working preferences window
- Initial window.py rewrite using Gtk.Builder
- Implement loading and error view

**TODO:**
- [ ] Fix Live Translation issues (related to history duplication and more 😂)
- [ ] Implement de Translate Accel preference on the translation logic
- [ ] Implement clear action
- [ ] Implement paste action
- [ ] Implement final translation progress feedback
- [ ] Create a custom widget for the lang selection based on the mockups
- [ ] Fix some styling issues

I know I'm missing something, so please let me know 😂

2020-10-05 08:09 UTC, fushinari requested changes
Sorry, I haven't had time to do a proper review. (I guess it's not an issue for now because it's still a draft anyway.) These are just some things I noticed right away.

About the "custom widget" for the language selection, have you seen my glade file on #40 ? It might not be necessary to make a custom widget. Just something that inherits from GtkListBoxRow would be enough to put into two liststores per Combo-Popover. The first liststore for recent languages and the second one for the full languages list. 

Translation progress feedback is what had me thinking the most. I ended up thinking that a spinner on the bottom right of the right textview would be enough but I'm still not really satisfied with it.

2020-10-05 11:43 UTC, rafaelmardojai commented
Minor issues, resolved.

Yeah, I was thinking to implement it similar to your glade file. But I was thinking making a "custom widget" will help us to reuse some code.

2020-10-05 13:24 UTC, fushinari commented
Some comments:
- Spacing and margin should probably be at least 12 for the first GtkBox.
- The GtkScrolledWindows will also need some styling. (I think you already know that)
- "Reproduce" button doesn't work as it did earlier. Actually, I'm not sure it works at all.
- Should the clear and paste buttons be linked? They're two distinct actions even if they're on the same TextView.
- The buttons under the Left TextView should probably be right-aligned.
- Tooltips for "Clear" and "Paste" buttons

Other things:
- "Copy to Clipboard" can now just be "Copy"
- "Reproduce" should probably be "Listen"

Current:
![Screenshot_20201005_183620](https://user-images.githubusercontent.com/28823274/95083122-b0763800-0739-11eb-801b-ed2d22b2df5c.png)

After the changes in my comments:
![Screenshot_20201005_185329](https://user-images.githubusercontent.com/28823274/95084865-18c61900-073c-11eb-94f0-3ae382599ba9.png)

2020-10-05 13:28 UTC, fushinari commented on src/main.py
> +from gi.repository import Gio, GLib, Gdk, Gtk, Handy
Gdk should be before Gio because alphabetical order.

2020-10-05 13:59 UTC, rafaelmardojai commented
Your commend had been adressed.

> "Reproduce" button doesn't work as it did earlier. Actually, I'm not sure it works at all.

It doesn't work if there's no text. I will fix it, so it's insensitive in that case.

2020-10-05 14:41 UTC, rafaelmardojai commented
Looking your screenshots, we should ship our own icon for switch language. The semantic of `object-flip-horizontal-symbolic` will broke ours depending on the icons theme.

2020-10-05 15:17 UTC, fushinari commented
> Looking your screenshots, we should ship our own icon for switch language. The semantic of `object-flip-horizontal-symbolic` will broke ours depending on the icons theme.

I don't think we should. Since Dialect is a GNOME app, I don't think we should be taking different icon packs into consideration. I'm using Breeze only because I'm on Plasma right now and actually, I think the Breeze icon is very descriptive too. (In fact, I love Breeze's monochrome icons more than anything. Everything else looks unprofessional now. :sweat_smile: Especially on LibreOffice. If I could, I'd use Adwaita with Breeze's monochrome set even on GNOME.)

2020-10-06 04:12 UTC, rafaelmardojai commented
I have implemented the new lang selectors. I have the feeling that I have broke something in the process, so please test 😂. There are still some things to polish, but at least it's working.

Now I'm going to sleep. 🤣😂

2020-10-06 13:39 UTC, fushinari commented
You didn't sleep??? :laughing:

2020-10-06 13:50 UTC, fushinari commented
My exams got over today. Is it okay if I commit directly into this branch or do you want to do this fully?

2020-10-06 14:08 UTC, rafaelmardojai commented
Fell free to push. Probably today and tomorrow I wouldn't be able to work on this, so any progress is welcome.

2020-10-06 14:19 UTC, fushinari commented
> Fell free to push. Probably today and tomorrow I wouldn't be able to work on this, so any progress is welcome.

Bring it as close as possible to the mockups right?

2020-10-06 14:36 UTC, rafaelmardojai commented
> Bring it as close as possible to the mockups right?

Yeah, but for the popover I don't think we need the selection check, since the button is already expressing the selected lang.

2020-10-06 14:39 UTC, fushinari commented
> Yeah, but for the popover I don't think we need the selection check, since the button is already expressing the selected lang.

Oh damn. Had just finished implementing it. :laughing: 

![image](https://user-images.githubusercontent.com/28823274/95216571-d968fc80-080f-11eb-9527-396d1d146cdd.png)

2020-10-06 14:46 UTC, fushinari commented
> Looks cool, so let's keep it sweat_smilesweat_smile

Wait really? :sweat_smile: I was gonna chuck it off because I found some weird bugs with it.

2020-10-06 14:49 UTC, rafaelmardojai commented
> Wait really? 😅 I was gonna chuck it off because I found some weird bugs with it.

That's why I avoided it 😂, so I will leave to you the choice.

2020-10-06 14:52 UTC, fushinari commented
Okay, i think the bug might be simple. I'll keep it if I can fix them reasonably quickly. Btw, I changed some of the design into this:
![image](https://user-images.githubusercontent.com/28823274/95217628-08cc3900-0811-11eb-9575-e95fa7dea222.png)

I'm a bit conflicted because this looks closer to the mockups but might have been better as it was earlier.

2020-10-06 15:01 UTC, rafaelmardojai commented
Also the mockups are just reference. The closeness depends on the real world  issues 😂😅

2020-10-06 15:19 UTC, fushinari commented
> Looks good. But in what it difer from the previous implementation? Have you removed the recent langs list?

It's there. Just tiny adjustments. Am a bit busy with other stuff too at the moment so work's going a tad slow. So, I've pushed the minor changes for now.

2020-10-06 16:09 UTC, fushinari commented
I just spent nearly 30 minutes debugging something only to find it's a GTK bug: https://gitlab.gnome.org/GNOME/gtk/-/issues/1779

2020-10-06 19:27 UTC, fushinari commented
![image](https://user-images.githubusercontent.com/28823274/95250605-f6b1c100-0837-11eb-9223-6012ba41d3a0.png)

We have a bug somewhere...

2020-10-06 19:32 UTC, fushinari commented
Current UI during translation:
![image](https://user-images.githubusercontent.com/28823274/95250913-6a53ce00-0838-11eb-898d-5ca7b87b7530.png)

I honestly love this entire design!

2020-10-06 19:55 UTC, rafaelmardojai commented
Yeah, looks awesome!

Could we make the whole right side insensitive during translation process?

2020-10-06 23:40 UTC, rafaelmardojai commented
You now why the popover slows down when there's a text translated?
Probably related to the recent list redrawing, but why only when a text has been translated?

I hope it's noticeable in this GIF:
![Peek 06-10-2020 18-34](https://user-images.githubusercontent.com/6210397/95271112-b08e3a80-0802-11eb-985b-08f42b4c9e4e.gif)

Note: We should clear the search entry when the popover is closed.

2020-10-06 23:47 UTC, rafaelmardojai commented
I think it's related to the permanent thread. But why?

2020-10-07 00:04 UTC, rafaelmardojai commented
Printing anything in the `while` fixes the issue. 😕😕

```python
while True:
    print('why?')
    if self.trans_queue:
        ...
```

2020-10-07 00:24 UTC, rafaelmardojai commented
Changing the thread to this should fix the issue:
```python
def run_translation(self):
    while self.trans_queue:
        # Code ...
    self.active_thread = None
```

But, so we will be having the virtual issue again?

2020-10-07 03:08 UTC, fushinari commented
> But why?

Probably because an if condition is constantly being checked. But that's in another thread, it shouldn't be impacting the GUI...

> Printing anything in the while fixes the issue.

That's really really odd...

> Changing the thread to this should fix the issue:
>
> But, do we will be having the virtual issue again?

If we do this, won't the thread need to be started again whenever there's another translation? That might be an even bigger hit in performance.

2020-10-07 03:28 UTC, fushinari commented
Btw, what do you mean by virtual issue?

2020-10-07 07:03 UTC, fushinari commented
I can't decide if this is better or worse...
![image](https://user-images.githubusercontent.com/28823274/95298129-352b9800-0899-11eb-8e6a-cf7d665f5f39.png)

2020-10-07 11:23 UTC, rafaelmardojai commented
> Btw, what do you mean by virtual issue?

The issue we wanted to fix with the permanent thread. But forget it, I don't think this is the case.

> I can't decide if this is better or worse...

What do you mean?

2020-10-07 11:26 UTC, fushinari commented
> What do you mean?

I added 2px extra top and bottom margins for the labels. I feel like there's wasted space now...

2020-10-07 11:31 UTC, rafaelmardojai commented
> I added 2px extra top and bottom margins for the labels. I feel like there's wasted space now...

Yeah, and the fact that we have a long list neither helps.

2020-10-07 11:37 UTC, rafaelmardojai commented
The clear action should also clear the right text and save all to history? 🤔

2020-10-07 14:38 UTC, rafaelmardojai commented
> The clear action should also clear the right text and save all to history?

Not really, I was writing half sleep. 😅😅

2020-10-07 16:33 UTC, fushinari commented
> Yeah, and the fact that we have a long list neither helps.

Yes, it looks neater when you look at it for a while but really, do we need that padding?

Btw, is the defaulting to Auto intended?

2020-10-07 18:15 UTC, rafaelmardojai commented
> Yes, it looks neater when you look at it for a while but really, do we need that padding?

Not really, it also looks good without the padding.

> Btw, is the defaulting to Auto intended?

No, it was the default before, so I keep it. And I don't really have a hard opinion about it.

2020-10-07 19:26 UTC, fushinari commented
Looking into the history duplication issue... What's actually happening is that whenever `ui_return` is triggered, it goes into `history_update` and then somehow triggers `text-changed` signal twice... We can work around it ofc, but maybe we should instead try to find out what exactly is happening here.

2020-10-07 19:40 UTC, fushinari commented
The history part is a rabbit hole full of issues... Might just rewrite that tomorrow if I get time...

2020-10-08 01:13 UTC, rafaelmardojai commented
I have pushed my responsive design experiment. The only issue I'm having is that the window doesn't shrink even when it has space. Any ideas? What I'm missing?

2020-10-08 01:15 UTC, rafaelmardojai commented
`700` px of width for the responsive rule is probably to much right?

2020-10-08 01:34 UTC, rafaelmardojai commented
`700` is fine, otherwise the UI wouldn't change when a language with long name is selected.

2020-10-08 02:08 UTC, rafaelmardojai commented
> I have pushed my responsive design experiment. The only issue I'm having is that the window doesn't shrink even when it has space. Any ideas? What I'm missing?

Sorry for being stupid sometimes, I just forgot to wrap the label in the network error view. 😂😂

2020-10-08 02:41 UTC, rafaelmardojai commented
The mobile version is looking like this:
![Captura de pantalla de 2020-10-07 21-39-54](https://user-images.githubusercontent.com/6210397/95408742-c9bbe780-08e5-11eb-9037-fbc09ec16992.png)

2020-10-08 05:17 UTC, fushinari commented
Looks great so far!

I found even more bugs with the history system... It has several types of crashes so far. Some even involving the X server. I have no idea what to do except rewrite. But i think I'll do that later.

2020-10-08 14:23 UTC, fushinari commented
I had reimplemented the history. It's mostly the same but with some tiny but huge (if that makes any sense) changes that should solve all the issues we're having. But here's the problem... I'm stuck at the loading screen for some reason...

2020-10-08 14:38 UTC, fushinari commented
Okay, it's not any changes I made... It's just eternally in the loading screen, which brings my attention to another matter, we need a timeout... What's happening is this: The line
```python
self.lang_speech = list(lang.tts_langs(tld='com').keys())
```
is simply not returning anything. Instead it just hangs. Quite possibly, it's just that my IP has been banned or something of the sort.

2020-10-08 15:09 UTC, rafaelmardojai commented
The TTS isn't even working, so I don't know if we should remove it at the end.

2020-10-08 22:36 UTC, rafaelmardojai commented
And if we keep TTS we should port it from pydub to GStreamer.

2020-10-09 03:51 UTC, fushinari commented
> The TTS isn't even working, so probably we should remove it at the end.

Actually, the TTS was working fine for me. But launching the application itself is a hit or miss.

2020-10-09 06:44 UTC, fushinari commented
After I finished the original rewrite of the history system, I realized it was still not working right. As I said earlier above:

> Looking into the history duplication issue... What's actually happening is that whenever ui_return is triggered, it goes into history_update and then somehow triggers text-changed signal twice... We can work around it ofc, but maybe we should instead try to find out what exactly is happening here.

Then once I worked that around (using a variable `history_traverse`), I found that many cases weren't handled properly yet. So, I added the needed handling.

But then I found a possibly better implementation. We can avoid the workaround too. The GtkTextBuffer signal `end-user-action` can be used. But I don't really know if it comes with any disadvantages so it might need more testing. Actually, all of it needs more testing. I'm surprised I didn't notice until just now exactly how broken the original history system was.

2020-10-09 09:57 UTC, fushinari commented
And with that, I'd say our work is almost done.

2020-10-09 10:20 UTC, rafaelmardojai commented
Nice! We should give us some time of testing and then we can merge this!

2020-10-09 10:27 UTC, rafaelmardojai commented on src/main.py
> +        Gst.init(None)  # Init Gst
We should init Gst right after the `gi.repository` import or it will fail in some setups.

2020-10-09 10:37 UTC, fushinari commented on src/main.py
> +        Gst.init(None)  # Init Gst
Oh? Are you sure? What's an example of such a setup? Afaik, that shouldn't be happening...

2020-10-09 10:43 UTC, rafaelmardojai commented on src/main.py
> +        Gst.init(None)  # Init Gst
I don't really know what comes to play to make that happen, but I had this issue in Blanket with a Manjaro user: https://github.com/rafaelmardojai/blanket/issues/6.

Lollypop for example, does the same: https://gitlab.gnome.org/World/lollypop/-/blob/master/lollypop/application.py#L20

2020-10-09 11:03 UTC, fushinari commented on src/main.py
> +        Gst.init(None)  # Init Gst
That shouldn't be impacting Dialect since there's no chance at all that we will touch Gst until after do_startup. In Blanket and in Lollypop, you're actually using it before the application startup is complete. (For example, in Blanket, during __init__)

2020-10-09 11:08 UTC, rafaelmardojai commented on src/main.py
> +        Gst.init(None)  # Init Gst
Yeah, you are right!

2020-10-09 11:09 UTC, fushinari commented
I think we need to kill the "Listen" feature. It works but I almost wish it didn't. The issue is that instead of speaking in a voice suitable for whatever language is selected, it speaks in the English US voice using the transliterated text. (For eg, in my language, Malayalam.)

2020-10-09 12:14 UTC, fushinari commented on src/window.py
> +            self.settings.set_value('left-langs',
This is making it really really slow to switch...

2020-10-09 12:19 UTC, rafaelmardojai commented on src/window.py
> +            self.settings.set_value('left-langs',
Yeah, we could save that when the window is closed.

2020-10-09 12:24 UTC, rafaelmardojai commented
Should we also show the selected lang in the recent list?

2020-10-09 14:13 UTC, fushinari commented on src/window.py
> +            self.settings.set_value('left-langs',
Yeah, I've switched to doing that.

2020-10-09 14:16 UTC, fushinari commented
Okay, only one bug left afaik.

2020-10-09 15:06 UTC, rafaelmardojai commented
We also save the left langs in the translation thread. We will keep that?

2020-10-09 15:19 UTC, fushinari commented
> We also save the left langs in the translation thread. We will keep that?

I have mixed feelings about that one, so I'm experimenting on its reliability.

2020-10-09 15:46 UTC, fushinari commented
I said one bug, but there are two major bugs:
1. When switching between desktop mode and mobile mode, the app often gets stuck in a weird in-between state.
![Screenshot from 2020-10-09 21-01-54](https://user-images.githubusercontent.com/28823274/95603939-9a87b080-0a74-11eb-8fa5-6fe19d1effb7.png)

2. When resized too quickly into a way too small size, the window disappears. It's still there, you just won't be able to see it.
![dialect](https://user-images.githubusercontent.com/28823274/95603786-60b6aa00-0a74-11eb-8d71-61cf43c0acaa.gif)

2020-10-09 16:02 UTC, rafaelmardojai commented
Yeah, I was able to reproduce the first yesterday.

The second looks very weird, I will try to reproduce it when I'm back at my computer.

2020-10-09 16:05 UTC, rafaelmardojai commented
I don't know if the first can be fixed changing the implementation from the GtkActionBar to a GtkRevealer with a GtkBox using custom CSS.

About the second we need to investigate, it can also be a libhandy bug.

2020-10-09 16:13 UTC, fushinari commented
I've been thinking. How about we stop using a loading screen and waiting specifically for the TTS? We could just use the already present Spinner and set a tooltip for voice_btn during the loading. This way, we could cut down on the loading times a lot.

2020-10-09 16:14 UTC, fushinari commented
> About the second we need to investigate, it can also be a libhandy bug.

I'm pretty sure it is. It seems similar to the modal drag bug that was present in earlier libhandy1 versions.

2020-10-09 16:16 UTC, fushinari commented
> About the second we need to investigate, it can also be a libhandy bug.

Weird thing is, you can't reproduce it in the "Loading" stack page.

2020-10-09 16:28 UTC, fushinari commented
Right now, I'm very hesitant to play with the GUI  because I use Glade 3.38 and it breaks compatibility with 3.22, which is what you seem to be using. So, every change I've made so far in the GUI (those minor stuff) have been in the XML directly. Even the Glade flatpak seems to be 3.36. So I have no idea what to do next.

2020-10-09 16:33 UTC, rafaelmardojai commented
> Right now, I'm very hesitant to play with the GUI  because I use Glade 3.38 and it breaks compatibility with 3.22, which is what you seem to be using. So, every change I've made so far in the GUI (those minor stuff) has been in the XML directly. Even the Glade flatpak seems to be 3.36. So I have no idea what to do next.

I used GNOME Builder buildin Glade to generate some parts in the beginning. But I prefer to edit the XML files directly, and that's what I have been doing 😅😂

2020-10-09 16:36 UTC, fushinari commented
> > Right now, I'm very hesitant to play with the GUI  because I use Glade 3.38 and it breaks compatibility with 3.22, which is what you seem to be using. So, every change I've made so far in the GUI (those minor stuff) has been in the XML directly. Even the Glade flatpak seems to be 3.36. So I have no idea what to do next.
> 
> I used GNOME Builder buildin Glade to generate some parts in the beginning. But I prefer to edit the XML files directly, and that's what I have been doing sweat_smilejoy

So... me editing it with Glade 3.38 is fine?

2020-10-09 16:47 UTC, rafaelmardojai commented
> So... me editing it with Glade 3.38 is fine?

Yeah, I also don't have the libhandy catalog installed so... 😅😅

The only issue I have with Glade is the unnecessary packaging properties it add to the GtkBox children 😅

2020-10-09 16:52 UTC, fushinari commented
> The only issue I have with Glade is the unnecessary packaging properties it add to the GtkBox children sweat_smile

I agree but it makes things somewhat easier if you ignore the issues. I also hate how it doesn't support the "margin" property.

2020-10-09 17:27 UTC, rafaelmardojai commented
> I agree but it makes things somewhat easier if you ignore the issues. I also hate how it doesn't support the "margin" property.

Yeah, and we can always cleanup the XML later.

2020-10-10 17:07 UTC, fushinari commented
I'll be sending in a huge commit soon.

2020-10-10 18:18 UTC, fushinari commented
That fixes one major bug (above mentioned no1) and introduces a minor warning:
```
(com.github.gi_lom.dialect:43889): Gtk-WARNING **: 23:32:27.010: Negative content width -19 (allocation 1, extents 10x10) while allocating gadget (node box, owner GtkBox)
```
[This](https://gitlab.gnome.org/GNOME/gtk/-/issues/1057) issue seems relevant. 

The biggest change is, we're not waiting for gTTS loading anymore. This hugely improves startup time and it also solves many bug risks. As a side effect, the lovely stack pages had to be removed since they're not in use anymore.

You were right, switching away from GtkActionBar to a GtkRevealer fixed the first of the weird bugs.

I also added a basic in-app notification system to solve some of the error-presenting issues we're having. It might need some more work, especially to maybe try and workaround the above-mentioned GTK bug. (We've been doing that a lot haven't we? Here's to hoping GTK4 makes it all better.)

I also confirmed that the second bug we discussed is Wayland-only.

The code right now isn't as clean as I'd like it to be but I hope to fix that later rather than now. I'm too tired for now. :sweat_smile: Gonna take a good long sleep now

2020-10-10 18:21 UTC, fushinari commented
Bigger question is, are all the changes for the better or am I missing something? Asking because I probably am :sweat_smile:

2020-10-11 02:23 UTC, rafaelmardojai commented
> That fixes one major bug (above mentioned no1) and introduces a minor warning:

Yeah, looks annoying, but at least is not a critical 😂

> The biggest change is, we're not waiting for gTTS loading anymore. This hugely improves startup time and it also solves many bug risks. As a side effect, the lovely stack pages had to be removed since they're not in use anymore.

Looks awesome! The only issue is that the Listen button becomes sensitive when the loading is finished.

> I also confirmed that the second bug we discussed is Wayland-only.

I was suspecting that. I use X.Org and wasn't able to reproduce the bug. 

There's also this bug:

![Captura de pantalla de 2020-10-10 21-02-57](https://user-images.githubusercontent.com/6210397/95668641-7394b180-0b3c-11eb-8f05-f600cf0a8346.png)

It's related to the selector popover begin set to the mobile mode buttons. This was fixed by the `mobile_mode = None` thing that was helping to setup everything correctly depending on the window size 😂. This can be fixed by calling `self.toggle_mobile_mode` at the end of `self.setup`.

Also, what's the difference from using `threading.Timer` or `GLib.timeout_add_seconds`?

2020-10-11 02:31 UTC, rafaelmardojai commented
Why are we doing the `second_buffer = self.right_buffer` thing instead of calling `self.right_buffer` directly?

2020-10-11 02:33 UTC, rafaelmardojai commented
Fixed the Listen button and popover issues.

2020-10-11 03:19 UTC, rafaelmardojai commented
More issues:

- If you close the window when the `load_lang_speech` thread is still running, the app will not terminate until the tread is done. Not a real "issue" but there is it. 😂
- [ ] The Copy and Listen buttons will become sensitive with the right text empty, because we make those sensitive in the `translation` function without checking.
- [ ] When the network connection is recovered, you can't translate the failed translation since it was already "translated" 😂.

2020-10-11 03:27 UTC, fushinari commented
> This can be fixed by calling self.toggle_mobile_mode at the end of self.setup.

I was planning to add it in anyway because I don't know if check-resize will be called when a mobile device forces its geometry on the app. (I don't know because I don't own the devices to test :sweat_smile: )

> Also, what's the difference from using threading.Timer or GLib.timeout_add_seconds?

I think they could work similarly if we make the function return False, but I simply prefer this. Most importantly, idle_add from the main thread has always resulted in slight performance drops so far. So, I'm trying to avoid that.

> Fixed the Listen button and popover issues.

Nice!

> Why are we doing the `second_buffer = self.right_buffer` thing instead of calling `self.right_buffer` directly?

Just remnants of the old code. Safely removable.

> If you close the window when the load_lang_speech thread is still running, the app will not terminate until the tread is done. Not a real "issue" but there is it.

Threads, so yeah. We'll let python do the garbage collection and such there. Forcing it to terminate it is not an option anyway.

>  The Copy and Listen buttons will become sensitive with the right text empty, because we make those sensitive in the translation function without checking.

Yes, I noticed immediately after pushing yesterday. :laughing: 

> When the network connection is recovered, you can't translate the failed translation since it was already "translated".

On a similar note, if the user gets back connectivity after `load_lang_speech` fails, he has no way to try again.

2020-10-11 03:27 UTC, fushinari commented
Plenty of rough edges, I know. Just wanted to make the necessary changes asap and then work on the issues that come with.

2020-10-11 03:32 UTC, rafaelmardojai commented
> Plenty of rough edges, I know. Just wanted to make the necessary changes asap and then work on the issues that come with.

Yes, also most of the issues were there before 😂

2020-10-11 03:41 UTC, fushinari commented
> Yes, also most of the issues were there before joy

Or we had bigger issues in their place :rofl: I mean, we didn't have any feedback at all even when translation fails entirely

2020-10-11 04:09 UTC, fushinari commented
> On a similar note, if the user gets back connectivity after load_lang_speech fails, he has no way to try again.

2020-10-11 04:41 UTC, rafaelmardojai commented
> How do we even solve this?

That's a tricky one.

I can think in having something that checks network connection in a time cycle when an error has been raised. But I don't have it clear.

2020-10-11 04:53 UTC, fushinari commented
> I can think in having something that checks network connection in a time cycle when an error has been raised. But I don't have it clear.

Keep a permanent thread (the translation thread isn't permanent anymore btw) that checks for basic connectivity and then, if basic connectivity is found tries to load the languages list again?

2020-10-11 05:07 UTC, rafaelmardojai commented
> Keep a permanent thread (the translation thread isn't permanent anymore btw) that checks for basic connectivity and then, if basic connectivity is found tries to load the languages list again?

Yeah, something like that.

2020-10-11 18:17 UTC, rafaelmardojai commented
I have been trying multiple ways to detect if there's connectivity, but all those keep failing when you start the app without connectivity. Also makes the translation fail even if the connection has comeback.

Current attemp:
```python
import socket
import time

while True:
    try:
        host = socket.gethostbyname('www.google.com')
        sock = socket.create_connection((host, 80), 2)
        sock.close()
        break # if we only want to call it once. 

    except Exception as exc:
        # print
    finally:
        time.sleep(5)
```

Ideas?

2020-10-11 19:16 UTC, fushinari commented
> I have been trying multiple ways to detect if there's connectivity, but all those keep failing when you start the app without connectivity. Also makes the translation fail even if the connection has comeback.

Sorry, but I probably won't be able to work on this for a few days, again. 

I've seen this being done before:
```python
try:
    socket.setdefaulttimeout(10)
    socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect(('8.8.8.8', '53'))
    return True
except socket.error as exc:
    print(exc)
    return False
``` 

That should be the fastest method.

Also, NetworkManager provides connectivity info on its DBUS API through `NMConnectivityState`. Don't know if that's reliable enough though...

> Also makes the translation fail even if the connection has comeback.

Wait how? That shouldn't be happening...

2020-10-12 03:02 UTC, fushinari commented
How about this? Even if the last attempt of whatever we're trying to do (translation or audio) failed, we keep the button sensitive, but when running the next time after a failure, we check for connectivity. So, if the last time failed, we'll have the warning icon feedback but not making it insensitive. In the case of audio, if lang list loading failed, we try to load it again, wait for that and then try to produce audio. This way, almost all cases should be handled.

2020-10-12 03:54 UTC, rafaelmardojai commented
> How about this? Even if the last attempt of whatever we're trying to do (translation or audio) failed, we keep the button sensitive, but when running the next time after a failure, we check for connectivity. So, if the last time failed, we'll have the warning icon feedback but not making it insensitive. In the case of audio, if lang list loading failed, we try to load it again, wait for that and then try to produce audio. This way, almost all cases should be handled.

I'm with you, that looks like the best approach for us!

2020-10-12 06:08 UTC, fushinari commented
![Screenshot from 2020-10-12 11-25-47](https://user-images.githubusercontent.com/28823274/95710156-bf9b3f80-0c7d-11eb-9afd-f5530abae029.png)

For all the hate Ubuntu gets, it's probably still the most polished-looking linux distro out there. Everything just looks right... Green is obviously and logically "suggested-action" for example. Sure it might break with more CSS, but for now, it's damn good. Also, the Yaru icon theme's monochrome icons are so damn pretty and they make more logical sense than Adwaita's icons. For example, the Sound OSD icon when going over the limit, the microphone icon, etc. Overall, I can see where their design team's efforts are going.

On a sidenote, is their any way to make GNOME behave like Plasma where scrolling on the microphone icon will increase microphone volume? Right now, scrolling on the microphone icon increases speaker volume... GNOME lacks polish in some of the things I traditionally expect it to be polished. (But it's polished in literally every other aspect...)

Don't know why I'm ranting about that here... But anyway, I tested the Ubuntu-like setup (with Yaru 20.10) to check if what you said might be true, about the horizontal flip icon being different. I wanted to ensure it wasn't different in at least the most used Linux distro. I also wanted to check how badly Yaru broke CSS. But turns out they don't break much ever since their switch to Adwaita base if you're using the expected versions of each component (like libhandy).

2020-10-12 09:26 UTC, fushinari commented
> I'm with you, that looks like the best approach for us!

I just realized... If we're doing this, we don't really need a connectivity check at all, do we?

2020-10-12 12:10 UTC, rafaelmardojai commented
> I just realized... If we're doing this, we don't really need a connectivity check at all, do we?

Nope, we don't need it.

2020-10-12 12:20 UTC, fushinari commented
> Nope, we don't need it.

Could you check if everything behaves as expected now?

2020-10-12 13:36 UTC, rafaelmardojai commented
When the Listen button fails it becomes insensitive. 
Also the connection will never recover if you start the app without connection, I feel it's some `urllib3` issue.

2020-10-12 13:48 UTC, rafaelmardojai commented
> For all the hate Ubuntu gets, it's probably still the most polished-looking linux distro out there. Everything just looks right... Green is obviously and logically "suggested-action" for example. Sure it might break with more CSS, but for now, it's damn good. Also, the Yaru icon theme's monochrome icons are so damn pretty and they make more logical sense than Adwaita's icons. For example, the Sound OSD icon when going over the limit, the microphone icon, etc. Overall, I can see where their design team's efforts are going.

Yeah, the app looks really nice there!

> On a sidenote, is their any way to make GNOME behave like Plasma where scrolling on the microphone icon will increase microphone volume? Right now, scrolling on the microphone icon increases speaker volume... GNOME lacks polish in some of the things I traditionally expect it to be polished. (But it's polished in literally every other aspect...) (edit: i opened an issue for this)

I never tried that feature in the microphone icon, but I supposed that it worked as the volume one. At least I would expect it to do nothing, instead of increasing speaker volume. 😂

2020-10-12 14:42 UTC, fushinari commented
> When the Listen button fails it becomes insensitive.

Listen button fails? Sorry, i don't understand. When you press the listen button, `ui_voice` is called. This will make the spinner insensitive for the duration of the action. Once the words have been spoken or it fails, it should go back to normal if other conditions are met. (second_text not being empty and the selected language being supported)

> Also the connection will never recover if you start the app without connection, I feel it's some `urllib3` issue.

Wait really? How exactly do I reproduce this? It seems to work fine for me.

> Edit: Super minor issue: `run_translation` sends a notification with a space after the `\n`.

Solved.

2020-10-12 14:51 UTC, rafaelmardojai commented
> Listen button fails? Sorry, i don't understand. When you press the listen button, ui_voice is called. This will make the spinner insensitive for the duration of the action. Once the words have been spoken or it fails, it should go back to normal if other conditions are met. (second_text not being empty and the selected language being supported)

I mean, when the voice download fails, the Listen button becomes insensitive, so you can't retry.
![Peek 12-10-2020 09-48](https://user-images.githubusercontent.com/6210397/95760250-65e04880-0c70-11eb-9818-0dedf8ba067f.gif)

2020-10-12 14:58 UTC, rafaelmardojai commented
> Wait really? How exactly do I reproduce this? It seems to work fine for me.

1. Disable internet connection from computer
2. Start Dialect
3. `load_lang_speech` will fail and console will print: 

    ```bash
    Error: Unable to get language list: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd8742f17d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
    ```
    Witch is an strange error. Probably related to something else in my side.

4. Enable internet connection again
5. Dialect can't even translate and `run_translation` keeps failing.

2020-10-12 15:12 UTC, rafaelmardojai commented
Also if you translate something and `load_lang_speech` is still loading, the Listen button will become sensitive. We probably need some `voice_loading` var to check.

Clicking the Listen button  in that state will not fail, but will start `load_lang_speech` again.

2020-10-12 15:16 UTC, fushinari commented
>     1. Disable internet connection from computer
> 
>     2. Start Dialect
> 
>     3. `load_lang_speech` will fail and console will print:
>        ```shell
>        Error: Unable to get language list: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd8742f17d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
>        ```
>        
>        
>        Witch is an strange error. Probably related to something else in my side.
> 
>     4. Enable internet connection again
> 
>     5. Dialect can't even translate and `run_translation` keeps failing.

Oh... this sounds like a DNS issue and it could be that I can't reproduce it because I use dnscrypt-proxy all the time...

2020-10-12 15:17 UTC, fushinari commented
> Also if you translate something and `load_lang_speech` is still loading, the Listen button will become sensitive. We probably need some `voice_loading` var to check.
> 
> Clicking the Listen button in that state will not fail, but will start `load_lang_speech` again.

Yeah, I messed this up badly. I found out only now...

2020-10-12 15:30 UTC, fushinari commented
@rafaelmardojai Could you check now? I should've covered most cases by now.

2020-10-12 15:33 UTC, fushinari commented
>     5. Dialect can't even translate and `run_translation` keeps failing.

I kept on trying to reproduce this. No dice. It just works as intended on my system:
```
Error: Unable to get language list: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd672200880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```

2020-10-12 15:39 UTC, rafaelmardojai commented
> I kept on trying to reproduce this. No dice. It just works as intended on my system:

That's the error expected, I don't know what I'm getting the `Temporary failure in name resolution` DNS thing.

2020-10-12 15:39 UTC, rafaelmardojai commented
> Could you check now? I should've covered most cases by now.

All looks good!

2020-10-12 15:56 UTC, fushinari commented
> That's the error expected, I don't know what I'm getting the `Temporary failure in name resolution` DNS thing.

Yeah, nothing we can do about a bug in googletrans or urllib anyway... You could test how exactly it happens and report it to googletrans or urllib.

> All looks good!

Good enough to review and merge? (After some cleanup ofc)

2020-10-12 16:03 UTC, fushinari commented
Technically, we'd already accomplished the original goal of the PR a long time ago lol

2020-10-12 16:06 UTC, rafaelmardojai commented
> Technically, we'd already accomplished the original goal of the PR a long time ago lol

😅😅😂

Yes, some cleanup and we are ready!

2020-10-12 16:09 UTC, rafaelmardojai commented
With this merged, we only need to find a new icon and we can release!

2020-10-12 17:01 UTC, fushinari commented
> With this merged, we only need to find a new icon and we can release!

Yeah.

There's something I'm conflicted about. `self.run_translation` is called in a daemon thread. It's the reason why Dialect doesn't exit immediately most of the time. But I'm not sure I want this behavior to change. For example, what if it exits while the history entry is being added?

2020-10-12 17:05 UTC, fushinari commented
I renamed "first" and "second" to "src" and "dest" for clarity... But now I'm thinking maybe I should've only changed it for src_language and dest_language, and not src_text and dest_text.

Also, should we be renaming left_buffer and right_buffer? I mean... they aren't really just left and right anymore are they?

2020-10-12 17:10 UTC, rafaelmardojai commented
> Also, should we be renaming left_buffer and right_buffer? I mean... they aren't really just left and right anymore are they?

Yes, if we're changing the left/right thing, we should change it every where.

2020-10-12 17:17 UTC, fushinari commented
Exiting should now be instant under normal circumstances.

2020-10-12 17:30 UTC, fushinari commented
What actually changed is that with daemon=True gone, the thread now exits by itself only when its job is complete. I don't know if that's better or worse tbh...

2020-10-12 18:02 UTC, fushinari approved these changes

2020-10-12 18:06 UTC, fushinari commented
And with that last bit of missing functionality added in, I think we're done! :tada: Please give a final review and merge. :)

2020-10-12 18:11 UTC, rafaelmardojai commented
> What actually changed is that with daemon=True gone, the thread now exits by itself only when its job is complete. I don't know if that's better or worse tbh...

As long as the window closes instantly, we shouldn't care 😂

2020-10-12 18:12 UTC, fushinari commented
> As long as the window closes instantly, we shouldn't care joy

True ig :rofl:

2020-10-12 18:33 UTC, rafaelmardojai commented
By default we set the same recent lang list for both sides, so the app starts with `English -> English` after installation, that's what we want?

2020-10-12 18:34 UTC, rafaelmardojai commented
Also when the same lang is select in both sides we do nothing, is fine keep it like that?

2020-10-12 20:09 UTC, rafaelmardojai commented
Pushed fixes for the issues commented above. Checkout and merge if is ready!

2020-10-12 20:13 UTC, rafaelmardojai commented
When this is merged, I will open a new PR enabling localization. When we release people might want to contribute locals.

2020-10-12 22:04 UTC, rafaelmardojai commented
Bug: The char count wouldn't be updated when you use the Clear button.

2020-10-12 22:21 UTC, rafaelmardojai commented
We have two minor issues with the live translation that you can see in the GIF.

1. I don't think we can do much to solve this: when you clear the src text by hand, always the last letter is translated. 
2.  When the dest text gets empty, Copy and Listen buttons are sensitive. 

![Peek 12-10-2020 17-09](https://user-images.githubusercontent.com/6210397/95794871-89c27f00-0cae-11eb-9c67-de5d8356c794.gif)

2020-10-12 22:54 UTC, rafaelmardojai commented
> 2. When the dest text gets empty, Copy and Listen buttons are sensitive.

Pushed a fix for this.

2020-10-12 22:55 UTC, rafaelmardojai commented
When the lang is changed in any selector, translation should be executed? At least in live translation?

2020-10-13 01:37 UTC, fushinari commented
> By default we set the same recent lang list for both sides, so the app starts with `English -> English` after installation, that's what we want?

I just found why gi-lom decided on the "Auto" language selection at start. It's from the Google Translate behavior, which is probably the behavior people will expect too. So maybe we should revert back to using Auto?

> When this is merged, I will open a new PR enabling localization. When we release people might want to contribute locals.

Awesome!

> When the lang is changed in any selector, translation should be executed? At least in live translation?

Yeah, let's do that.

> I don't think we can do much to solve this: when you clear the src text by hand, always the last letter is translated.

This is the weirdest bug so far. I thought end-user-action might not be getting emitted properly. But turns out that works fine. Then I looked for other failures. Nope. Everything's fine and `self.dest_buffer.set_text('')` does get executed... I have no idea what's going on here...

2020-10-13 02:06 UTC, fushinari commented
I don't understand why it was happening, but now I can pretend I actually fixed it :laughing:

2020-10-13 03:32 UTC, rafaelmardojai commented
> I just found why gi-lom decided on the "Auto" language selection at start. It's from the Google Translate behavior, which is probably the behavior people will expect too. So maybe we should revert back to using Auto?

Yeah, I'm fine with that, it's a good default.

2020-10-13 03:48 UTC, merged