Search provider
gi-lom/dialect pull request #59
Opened 2020-10-18 19:57 UTC by nexeleriot

Search provider to translate in overview
Translates auto detected language into last used language

2020-10-18 20:17 UTC, rafaelmardojai commented
Could you install the search provider directly with meson?

Lollypop is a nice example: https://gitlab.gnome.org/World/lollypop/-/tree/master/search-provider

2020-10-18 20:30 UTC, fushinari requested changes
It's 2 AM here and I'm a little sleepy, so I've only skimmed through the changes. I'll properly test it later.

There's obviously some duplicated code here that we might want to refactor in the future, but for now, I think this will mostly work just fine.

It says "changes requested" like it's a big deal but other than the packaging issue, it's not.

2020-10-18 20:30 UTC, fushinari commented on build-aux/meson/postinstall.py
> -
A trailing newline is good. Don't remove it.

2020-10-18 20:30 UTC, fushinari commented on build-aux/meson/provider_postinstall.py
> +# user = environ.get('SUDO_USER')
I think you forgot to remove the commented out code here.

2020-10-18 20:30 UTC, fushinari commented on data/search_provider/search_provider.py
> +        pass
This isn't needed in this PR but I'm just writing it here so that I remember: we need to make this so that activating it will launch Dialect with the text pre-inserted.

2020-10-18 20:30 UTC, fushinari commented on src/meson.build
> -
That newline is for separating the directories from the imports. It's cleaner that way.

2020-10-18 20:30 UTC, fushinari commented on data/search_provider/install_search_provider.sh
> +install -Dm 0755 search_provider.py /usr/local/share/dialect/dialect/search_provider.py
Hardcoding the path is not gonna work for packaging. So you should use the meson prefix here.

2020-10-18 20:33 UTC, fushinari commented on data/search_provider/install_search_provider.sh
> +install -Dm 0755 search_provider.py /usr/local/share/dialect/dialect/search_provider.py
Or better yet, like @rafaelmardojai suggested, just use meson to install it.

2020-10-18 20:36 UTC, nexeleriot commented on data/search_provider/install_search_provider.sh
> +install -Dm 0755 search_provider.py /usr/local/share/dialect/dialect/search_provider.py
Yeah, i had some issues with installing with meson, but I was sleepy. I'll try meson one more time

2020-10-19 13:21 UTC, rafaelmardojai requested changes

2020-10-19 13:21 UTC, rafaelmardojai commented on search_provider/search_provider.in
> +#!/usr/bin/python3
```suggestion
#!@PYTHON@
```
You should use the meson provided python path here. Just for standardization.

2020-10-19 14:43 UTC, fushinari reviewed
Just minor nitpicks.

2020-10-19 14:43 UTC, fushinari commented on build-aux/meson/provider_postinstall.py
> +sleep(1)
Why the `sleep`?

2020-10-19 14:43 UTC, fushinari commented on build-aux/meson/postinstall.py
> -
Still there.

2020-10-19 14:43 UTC, fushinari commented on search_provider/search_provider.in
> +        else:
Unnecessary else after return. Use a newline and indent the next lines one step less.

2020-10-19 16:57 UTC, nexeleriot commented on build-aux/meson/provider_postinstall.py
> +sleep(1)
Gnome was enabling provider after disable it. I thought that Gnome does it after some time, but now I see that this code works bad so i will change it

2020-10-19 17:02 UTC, nexeleriot commented on search_provider/search_provider.in
> +#!/usr/bin/python3
Ok

2020-10-19 17:05 UTC, rafaelmardojai commented on build-aux/meson/provider_postinstall.py
> +sleep(1)
Are we going to be able to change this preference under Flatpak?

Also looks like Flatpaks with search providers are not enabled by default. Because I have that behavior and I only install Flatpaks.

2020-10-19 17:47 UTC, nexeleriot commented on build-aux/meson/provider_postinstall.py
> +sleep(1)
We can add some code into search_provider.in file to check if live translation is turned on for users who don't use Flatpak version. In Flatpak theese changes might be ignored

2020-10-19 21:10 UTC, nexeleriot commented
I think it is a good idea checking for live translation option instead of disabling provider. This check is only at the beginning of input

2020-10-19 21:14 UTC, nexeleriot commented
Also trere won't be problems with access to gnome settings from Flatpak

2020-10-20 09:43 UTC, fushinari approved these changes
Looks good now. I don't know how well it works because I'm using Plasma at the moment (thanks to fractional scaling issues on GNOME). But the code looks good.

2020-10-20 12:21 UTC, fushinari commented
I've tested it and it seems to work well for the most part. But I feel like launching Dialect when activated is the expected behavior.

How difficult would it be for you to make it so that activating the item will launch Dialect with the requested translation already in it? If you don't feel like doing it, I'll add it some time later.

2020-10-20 12:30 UTC, nexeleriot commented
I just need to add an argument with text to Dialect. I think it won't be hard

2020-10-20 13:16 UTC, rafaelmardojai approved these changes
We also need to advice the user in some way. The search provider depending in the live translation is a bit strange in a UX PoV, but we don't have many options here, having a preference for this in the app will also duplicate the one in GNOME Settings. 

Would be nice if we could opt to set the search disabled by default in the `.ini` file. 😕

2020-10-20 13:37 UTC, nexeleriot commented
Unfortunately GNOME doesn't contain it in .ini
Maybe we can name preference something like "Live translation and translation in overview "

2020-10-20 13:51 UTC, fushinari commented
We can't enable it by default either for the same reasons that Live Translation is disabled by default... We could add it to the subtitle label for the Live Translation option and make it two lines, but I feel it won't look good.

2020-10-22 16:02 UTC, nexeleriot commented
> I just need to add an argument with text to Dialect. I think it won't be hard

I'm sorry I can't work now because of study, so I can't do it now

2020-10-22 19:24 UTC, fushinari commented
Ah, too bad. Thanks for the work. One of us will implement it later, so no worries.

2020-10-22 19:25 UTC, merged